/* HTML template loaded by index.ssjs; serving this JS file directly is inert. */
var CT_COMMUNICATOR_PAGE = [
'<!doctype html>',
'<html lang="en">',
'<head>',
'  <meta charset="utf-8">',
'  <meta name="viewport" content="width=device-width, initial-scale=1">',
'  <meta name="theme-color" content="#091417">',
'  <title>Captain\'s Portable Communicator</title>',
'  <link rel="stylesheet" href="communicator.css">',
'</head>',
'<body>',
'  <main class="device" aria-labelledby="device-title">',
'    <div class="grille" aria-hidden="true"></div>',
'    <header class="device-header">',
'      <div class="manufacturer">CEPHEUS NAVAL WORKS</div>',
'      <h1 id="device-title">Portable Communicator</h1>',
'      <div class="serial">CAPTAIN\'S UNIT · SECURE BURST RECEIVER</div>',
'    </header>',
'',
'    <section class="screen" aria-live="polite">',
'      <div class="screen-topline">',
'        <span>BRIDGE RELAY</span>',
'        <span id="signal">STANDBY</span>',
'      </div>',
'      <div id="notice-panel" class="notice-panel" hidden>',
'        <div class="notice-label">PRIORITY TRANSMISSION</div>',
'        <h2 id="notice-title"></h2>',
'        <p id="notice-body"></p>',
'        <dl id="notice-detail"></dl>',
'      </div>',
'      <div id="status-panel">',
'        <div class="scope" aria-hidden="true">',
'          <span></span><span></span><span></span>',
'          <i></i>',
'        </div>',
'        <h2 id="status-title">Opening relay channel…</h2>',
'        <p id="status-text">Keep this unit nearby while the ship establishes contact.</p>',
'      </div>',
'    </section>',
'',
'    <section id="enrollment" class="controls" hidden>',
'      <p class="instruction">This receiver has a fresh pairing signal from your active game session. Link it to receive bridge calls while you are away.</p>',
'      <button id="link-button" class="primary" type="button">Link this communicator</button>',
'    </section>',
'',
'    <section id="settings" class="controls" hidden aria-labelledby="settings-title">',
'      <h2 id="settings-title">Receiving Orders</h2>',
'      <label><input id="attention-soon" type="checkbox"> Warn before I will be needed</label>',
'      <div class="lead-row">',
'        <label for="lead-minutes">Advance warning</label>',
'        <input id="lead-minutes" type="number" min="1" max="1440" value="5">',
'        <span>minutes</span>',
'      </div>',
'      <label><input id="attention-now" type="checkbox"> Call me when the captain must act</label>',
'      <div class="button-row">',
'        <button id="save-button" class="primary" type="button">Set receiving orders</button>',
'        <button id="revoke-button" class="danger" type="button">Unlink this unit</button>',
'      </div>',
'    </section>',
'',
'    <footer>',
'      <span>ENCRYPTED SHIP-TO-SHORE CIRCUIT</span>',
'      <span class="lamp"><i></i> RELAY</span>',
'    </footer>',
'  </main>',
'  <script src="communicator.js"></script>',
'</body>',
'</html>',
''
].join('\n');
