set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CT_MINGW_TRIPLE x86_64-w64-mingw32 CACHE STRING "MinGW target triple")
set(CMAKE_C_COMPILER "${CT_MINGW_TRIPLE}-gcc")
set(CMAKE_CXX_COMPILER "${CT_MINGW_TRIPLE}-g++")
set(CMAKE_RC_COMPILER "${CT_MINGW_TRIPLE}-windres")
